// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function InitializeNodeArray(arg1:types.NodesWithId,arg2:string,arg3:string):Promise<Array<types.ResolutionNode>>;

export function ReconstructPath(arg1:Array<types.ResolutionNode>):Promise<Array<string>>;

export function Step(arg1:types.NodesWithId,arg2:types.EdgesWithId,arg3:Array<types.ResolutionNode>,arg4:number):Promise<types.StepResult>;
