// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitializeNodeArray(arg1, arg2, arg3) {
  return window['go']['services']['LongestPath']['InitializeNodeArray'](arg1, arg2, arg3);
}

export function ReconstructPath(arg1) {
  return window['go']['services']['LongestPath']['ReconstructPath'](arg1);
}

export function Step(arg1, arg2, arg3, arg4) {
  return window['go']['services']['LongestPath']['Step'](arg1, arg2, arg3, arg4);
}
