// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RandomGraph(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['Randomizer']['RandomGraph'](arg1, arg2, arg3, arg4, arg5);
}

export function RandomGraphJS(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['Randomizer']['RandomGraphJS'](arg1, arg2, arg3, arg4, arg5);
}
