// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function RandomGraph(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<types.NodesWithId>;

export function RandomGraphJS(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<Record<string, any>>;
